version: '3.8'

services:
  app:
    build: .
    ports:
      - "5001:5001"  # HostPort:ContainerPort
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    command: npm run dev  # Override Dockerfile CMD

  mongo:
    image: mongo:8.0
    container_name: mongo
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: