[[entries."src/Controller/BlogController.php".issues]]
code = "braced-string-interpolation"
start_line = 21
end_line = 21

[[entries."src/Controller/BlogController.php".issues]]
code = "no-literal-password"
start_line = 18
end_line = 18

[[entries."src/Controller/ToolsController.php".issues]]
code = "final-controller"
start_line = 10
end_line = 10

[[entries."src/Controller/appController.php".issues]]
code = "class-name"
start_line = 10
end_line = 10

[[entries."src/Controller/appController.php".issues]]
code = "final-controller"
start_line = 10
end_line = 10
