controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute




when@production:
    tools:
        path: /tools
        controller: App\Controller\ToolsController::index
